name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: dante-ev/latex-action@latest
        with:
          root_file: zklayer-whitepaper.tex
      - name: Save artifact
        uses: actions/upload-artifact@v4
        with:
          name: whitepaper.pdf
          path: zklayer-whitepaper.pdf


